version: '3'
services:
  db:
    image: postgres
    container_name: db_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - my_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  my_pgdata: